# Generated by Django 6.0.6 on 2026-07-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
