# Generated by Django 6.0.6 on 2026-07-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school1', '0004_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='fee_type',
            field=models.CharField(choices=[('Tuition', 'Tuition'), ('Transport', 'Transport'), ('Exam', 'Exam'), ('Library', 'Library'), ('Hostel', 'Hostel'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='finance',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
