# Generated by Django 6.0.6 on 2026-08-15 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school1', '0009_bookauthor_bookcopy_bookedition_booklanguage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('transaction_type', models.CharField(choices=[('Receipt', 'Receipt'), ('Expense', 'Expense'), ('Both', 'Receipt/Expense')], default='Both', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school1.pettycashcategory')),
            ],
            options={
                'verbose_name_plural': 'Petty cash categories',
            },
        ),
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Receipt', 'Receipt'), ('Expense', 'Expense')], max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Online', 'Online')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('party_person', models.CharField(blank=True, max_length=150)),
                ('comments', models.TextField(blank=True)),
                ('invoice', models.FileField(blank=True, upload_to='petty_cash/invoices/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school1.pettycashcategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school1.department', verbose_name='School/Department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school1.employee')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school1.student')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
